### ISSUE TITLE
ArchiveからTodoへ移動するとナンバリングがおかしくなるバグ

### ISSUE THREAD

**Issue by tkyshm** [mizkei/yalzo#13]
ArchiveからTodoに移動するとTodo構造体のnoにあたる値がおかしい

**Comment by mizkei** [comment]
https://github.com/mizkei/yalzo/commit/3b8e23586660d889449bb610ff21bdc980741495#diff-3fec8f1c0b392bacddcb2a81eb8ad937
上記のコミットにより、todoとarchiveの移動動作は同一となりました
したがって、以下の問題に集約します
https://github.com/mizkei/yalzo/issues/16

**Comment by tkyshm** [comment]
こっちはcloseしときます
