### ISSUE TITLE
一番最後のTODOをDeleteした後に別のTODOを削除すると落ちる

### ISSUE THREAD

**Issue by tkyshm** [mizkei/yalzo#14]
最後のTODOをスペースで選択してから<C-d>で削除した後、
別のTODOを同様に削除を実施したところ無事に強制終了

**Comment by mizkei** [comment]
削除の際のインデックス指定の問題でした

https://github.com/mizkei/yalzo/commit/3b8e23586660d889449bb610ff21bdc980741495
上記のコミットで修正済みです
