### ISSUE TITLE
初期設定ファイルが存在しない場合は自動生成したい

### ISSUE THREAD

**Issue by tkyshm** [mizkei/yalzo#19]
初期設定ファイル(.yalzo以下のファイル)が存在しない場合はエラーで起動しない。
初期設定ファイルは自動生成して何も考えなくても使えるようにしたい。

**Comment by mizkei** [comment]
対応しました
https://github.com/mizkei/yalzo/commit/3e8417e3cbf10edf075e67ac8cbff6e080ea61b0#diff-31583338580717d5a16fb0af0ec66abf
