### ISSUE TITLE
Todo（Archive含む）が空の時にC-aを押すと落ちる

### ISSUE THREAD

**Issue by tkyshm** [mizkei/yalzo#24]
空の状態でTodoの移動をすると落ちる
また、C-dでも落ちる

**Comment by mizkei** [comment]
下記の修正で対応しました
https://github.com/mizkei/yalzo/commit/7f3d4469dbe0d8e35163ae17416ddf07e155306c
https://github.com/mizkei/yalzo/commit/ab50f889a9f36409c352c9862b2648d560fda86e
