### ISSUE TITLE
UIの改善

### ISSUE THREAD

**Issue by tkyshm** [mizkei/yalzo#29]
ユースケースの見直しと無駄にキーバインドを増やしたくない要望です。
- [x] C-vで一度ラベル追加したら戻る -> 連続で追加したいケースもあるので戻らない とする
- [x] C-vでラベル編集モードに移行して追加・削除のキーバインドは統一させる

**Comment by tkyshm** [comment]
完了したらチェックつける

**Comment by mizkei** [comment]
実装をおこないました
https://github.com/mizkei/yalzo/commit/82bacd2f5747aeef1332e46753140ede46d8f3e2
